apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-game-deployment
  labels:
    app: nginx-game
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-game
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  progressDeadlineSeconds: 60
  template:
    metadata:
      labels:
        app: nginx-game
    spec:
      containers:
        - name: nginx-game
          image: testsysadmin8/nginx-game:latest
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "250m"
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
