apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-game-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-game
  template:
    metadata:
      labels:
        app: nginx-game
    spec:
      containers:
      - name: nginx-game-container
        image: testsysadmin8/nginx-game:latest
        ports:
        - containerPort: 80
 
